import { Button, LineEdit, CheckBox, VerticalBox, HorizontalBox, ProgressIndicator } from "std-widgets.slint";

export component AppWindow inherits Window {
    width: 500px;
    height: 300px;
    title: "SecuraFolder";

    in-out property <string> pass: "";
    in-out property <bool> is_encrypted: true;
    in-out property <float> progress: 0.0;
    callback submit();

    VerticalBox {
        spacing: 15px;
        padding: 10px;

        HorizontalBox {
            height: 50px;
            alignment: center;
            Text {
                text: "SecuraFolder";
                font-size: 18px;
            }
        }

        pass_component := LineEdit {
            placeholder-text: "Enter password";
            input-type: password;
        }

        conf_component := LineEdit {
            placeholder-text: "Confirm password";
            input-type: password;
        }

        ProgressIndicator {
            width: 100%;
            height: 20px;
            progress: root.progress;
        }

        popup := PopupWindow {
            Rectangle {
                height: 100%;
                width: 100%;
                background: red;
            }
            VerticalBox {
                width: 100%;
                height: 100%;

                Text {
                    text: "The two passwords didn't match, please retry";
                    font-size: 16px;
                    color: black;
                }
            }
            x: 20px; y: 20px; height: 50px; width: 50px; close-policy:close-on-click-outside;
        }

        Button {
            checkable: true;
            checked: !is_encrypted;
            text: is_encrypted ? "Currently Encrypted | Start Decryption" : "Currently Decrypted | Start Encryption";
            clicked => {
                if (pass_component.text == conf_component.text) {
                    root.pass = pass_component.text;
                    if (self.checked) {
                        root.is_encrypted = false;
                    }
                    else {
                        root.is_encrypted = true;
                    }
                    root.submit();
                }
                else {
                    self.checked = !self.checked;
                    popup.show()
                }
            }
        }
    }
}
